apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: sample-2
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sample-2
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-ex.git'
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'ruby:2.7'
        namespace: openshift
      env: []
  output:
    to:
      kind: "ImageStreamTag"
      name: "sample-2:latest"
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: sample-2-pending
spec:
  source:
    type: Git
    git:
      uri: 'https://github.com/openshift/ruby-ex.git'
      ref: master
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'ruby:2.7'
        namespace: openshift
      env: []
  output:
    to:
      kind: "ImageStreamTag"
      name: "sample-2-does-not-exist:latest"
